name = "lingering-brook-a115"                # replace with your worker name
workers_dev = true
compatibility_date = "2025-10-23"

main = "./dist/index.mjs"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "email-store"
database_id = "80953319-1700-4c6a-baa3-64700f3cdc75"